# Generated by Django 3.0.4 on 2020-04-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discourseAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_groups',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_groups',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
