# Generated by Django 3.0.4 on 2020-03-23 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discourseAdmin', '0002_auto_20200323_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='groups',
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='discourseAdmin.User_Groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_groups',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
