# Generated by Django 3.0.4 on 2020-04-10 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discourseAdmin', '0002_auto_20200409_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='discourseAdmin.dGroup'),
        ),
    ]
