# Generated by Django 3.0.4 on 2020-04-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discourseAdmin', '0003_auto_20200410_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dgroup',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='dgroup',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
