# Generated by Django 3.0.4 on 2020-03-23 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discourseAdmin', '0003_auto_20200323_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
    ]
