# Generated by Django 3.0.4 on 2020-03-23 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discourseAdmin', '0004_remove_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='discourseAdmin.User_Groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
