# Generated by Django 3.0.4 on 2020-04-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discourseAdmin', '0004_auto_20200410_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='dgroup',
            name='discourse_group_id',
            field=models.IntegerField(null=True),
        ),
    ]
