# Generated by Django 3.0.4 on 2020-03-23 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discourseAdmin', '0005_group_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_groups',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='user_groups',
            old_name='user_id',
            new_name='user',
        ),
    ]
