# Generated by Django 3.0.4 on 2020-04-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discourseAdmin', '0005_dgroup_discourse_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dgroup',
            name='discourse_group_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
