# Generated by Django 3.0.4 on 2020-06-01 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discourseAdmin', '0006_auto_20200414_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='dgroup',
            name='is_department',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dgroup',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='discourseAdmin.dGroup'),
        ),
        migrations.AlterField(
            model_name='user_groups',
            name='rights',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='user_groups',
            unique_together={('user', 'group')},
        ),
    ]
