# Generated by Django 3.0.4 on 2020-03-23 16:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discourseAdmin', '0006_auto_20200323_1327'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='dGroup',
        ),
    ]
